config/routes.rb
          put :menu_links, to: "communities#update_topbar" # PUT request, no redirect

          get :getting_started, to: redirect('/admin/getting_started_guide')

          get :edit_details,       to: redirect("/admin/details/edit")
          put :update_details,     to: "community_customizations#update_details" # PUT request, no redirect
          get :edit_look_and_feel, to: redirect("/admin/look_and_feel/edit")
          put :edit_look_and_feel, to: "community_customizations#update_look_and_feel" # PUT request, no redirect

          get :settings,       to: redirect("/admin/settings")
          put :update_settings # PUT request, no redirect
          get "getting_started_guide",                        to: redirect("/admin/getting_started_guide")
          get "getting_started_guide/slogan_and_description", to: redirect("/admin/getting_started_guide/slogan_and_description")
          get "getting_started_guide/cover_photo",            to: redirect("/admin/getting_started_guide/cover_photo")
          get "getting_started_guide/filter",                 to: redirect("/admin/getting_started_guide/filter")
          get "getting_started_guide/paypal",                 to: redirect("/admin/getting_started_guide/paypal")
          get "getting_started_guide/listing",                to: redirect("/admin/getting_started_guide/listing")
          get "getting_started_guide/invitation",             to: redirect("/admin/getting_started_guide/invitation")

        end
        resources :listings, controller: :community_listings, only: [:index, :edit, :update] do
          member do
            get :approve
            get :reject
          end
          collection do
            get 'export'
            get 'export_status'
          end
        end
        resources :transactions, controller: :community_transactions, only: [:index, :show] do
          collection do
            get 'export'
            get 'export_status'
          end
          member do
            get :confirm
            get :cancel
            get :refund
            get :dismiss
          end
        end
        resources :conversations, controller: :community_conversations, only: [:index, :show]
        resources :testimonials, controller: :community_testimonials, only: [:index, :edit, :update, :new, :create] do
          collection do
            get :new_unskip
            post :unskip
          end
        end
        resources :invitations, controller: :community_invitations, only: [:index]
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :unban
            put :resend_confirmation
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do

          member do
            get :index,                to: redirect("/admin/paypal_preferences")
            post :preferences_update   # POST request, no redirect
            get :account_create,       to: redirect("/admin/paypal_preferences/account_create")
            get :permissions_verified, to: redirect("/admin/paypal_preferences/permissions_verified")
          end
        end
      end
      resources :custom_fields do
        collection do
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
          get :edit_expiration
          put :update_expiration
        end
      end
      resources :person_custom_fields, path: 'user_fields' do
        collection do
          post :order
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
      resource :plan, only: [:show]
      resource :domain, only: [:show, :update] do
        collection do
          get :check_availability
        end
      end
      resource :community_seo_settings, only: [:show, :update]
      resources :landing_page_versions do
        member do
          get :release
        end
        resources :sections, controller: 'landing_page_versions/sections'
      end
    end

    resources :invitations, only: [:new, :create ] do
      collection do
        get :unsubscribe
      end
    end
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        post :join
      end
    end

    resources :listings do
      member do
        post :follow
        delete :unfollow
        delete :delete
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments, :only => [:create, :destroy]
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
          put :reorder
        end
      end
      resources :preauthorize_transactions, only: [], defaults: { format: :json } do
        member do
          post :stripe_confirm_intent
          post :stripe_failed_intent
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, skip: :omniauth_callbacks, controllers: { confirmations: "confirmations", registrations: "people", omniauth_callbacks: "omniauth"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      get "/people/sign_up" => redirect("/%{locale}/login")

      get "/signup" => "people#new", :as => :sign_up

      resources :people, param: :username, :path => "", :only => :show, :constraints => { :username => /[_a-z0-9]{3,20}/ }

      resources :people, except: [:show] do
        collection do
          get :check_email_availability
          get :check_email_availability_and_validity
          get :check_invitation_code
        end
        member do
          get :check_username_availability
        end
      end

      resources :people, except: [:show], :path => "" do
        resources :listings do
          member do
            put :close
            put :move_to_top
            put :show_in_updates_email
          end
          collection do
            get :new_form_content
          end
        end
        resources :person_messages

        resource :inbox, :only => [:show]

        resources :messages, :controller => :conversations do
          collection do
            get :received, to: 'inboxes#show'
          end
          member do
            get :confirm, to: 'confirm_conversations#confirm'
            get :cancel, to: 'confirm_conversations#cancel'
            put :confirmation, to: 'confirm_conversations#confirmation' #TODO these should be under transaction
            get :accept_preauthorized, to: 'accept_preauthorized_conversations#accept'
            get :reject_preauthorized, to: 'accept_preauthorized_conversations#reject'
            put :acceptance_preauthorized, to: 'accept_preauthorized_conversations#accepted_or_rejected'
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end
          end
        end
        resource :paypal_account, only: [:index] do
          member do
            get :ask_order_permission
            get :ask_billing_agreement
            get :permissions_verified
            get :billing_agreement_success
            get :billing_agreement_cancel
          end
        end
        resource :stripe_account, only: [:show, :update, :create] do
          member do
            put :send_verification
          end
        end

        resources :transactions, only: [:show, :new, :create]
        resource :settings do
          member do
            get :account
            get :notifications
            get :unsubscribe
            get :listings
            get :transactions
          end
        end
        resources :testimonials
        resources :emails do
          member do
            post :send_confirmation
          end
        end
        resources :followers
        resources :followed_people
      end # people

    end # devise scope person

    get "/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation

    get '/:person_id/settings/profile', to: redirect("/%{person_id}/settings") #needed to keep old links working

  end # scope locale

  id_to_username = Proc.new do |params, req|
    username = Person.find(params[:person_id]).try(:username)
    locale = params[:locale] + "/" if params[:locale]
    if username
      "/#{locale}#{username}#{params[:path]}"
    else
      "/404"
    end
  end

  get "(/:locale)/people/:person_id(*path)" => redirect(id_to_username), :constraints => { :locale => locale_matcher, :person_id => /[a-zA-Z0-9_-]{22}/ }

app/models/landing_page_version.rb
# == Schema Information
#
# Table name: landing_page_versions
#
#  id           :integer          not null, primary key
#  community_id :integer          not null
#  version      :integer          not null
#  released     :datetime
#  content      :text(16777215)   not null
#  created_at   :datetime
#  updated_at   :datetime
#
# Indexes
#
#  index_landing_page_versions_on_community_id_and_version  (community_id,version) UNIQUE
#

class LandingPageVersion < ApplicationRecord
  include LandingPageVersion::DataStructure

  belongs_to :community
end

app/models/landing_page_version/data_structure.rb
module LandingPageVersion::DataStructure
  extend ActiveSupport::Concern

  def sections
    return @sections if defined?(@sections)

    sections = []
    parsed_content['sections'].each do |content_section|
      case content_section['kind']
      when LandingPageVersion::Section::HERO
        sections << LandingPageVersion::Section::Hero.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::FOOTER
        sections << LandingPageVersion::Section::Footer.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::INFO
        sections << LandingPageVersion::Section::Info.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::LISTINGS
        sections << LandingPageVersion::Section::Listings.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::CATEGORIES
        sections << LandingPageVersion::Section::Categories.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::LOCATIONS
        sections << LandingPageVersion::Section::Locations.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      when LandingPageVersion::Section::VIDEO
        sections << LandingPageVersion::Section::Video.new_from_content(content_section.merge(
            'landing_page_version' => self,
            'previous_id' => content_section['id']
          ))
      end
    end
    @sections = sections
  end

  def section_positions
    return @section_positions if defined?(@section_positions)

    existing_sections = parsed_content['sections'].dup
    composition = parsed_content['composition'].dup
    section_positions = []
    composition.each_with_index do |item, index|
      section_id = item['section']['id']
      existing_section = existing_sections.find{|x| x['id'] == section_id}
      next unless existing_section

      attrs = existing_section.slice('id', 'kind', 'variation')
      attrs['position'] = index
      section_positions << LandingPageVersion::SectionPosition.new(attrs)
    end
    @section_positions = section_positions
  end

  def section_positions_attributes=(section_positions_params)
    composition = []
    section_positions_params.values.sort_by { |a| a['position'].to_i }.each do |section_position|
      composition << { 'section' => {'type' => 'sections', 'id' =>  section_position['id'] }}
    end
    new_content = parsed_content.dup
    new_content['composition'] = composition
    update_content(new_content)
  end

  def parsed_content
    @parsed_content ||= JSON.parse(content)
  end

  def update_content(new_content)
    @parsed_content = nil

    # ensure hero is first and footer is last
    composition = new_content['composition']
    hero = composition.find{|x| x['section']['id'] == 'hero' }
    footer = composition.find{|x| x['section']['id'] == 'footer' }
    inner_content = composition.select{|x| x != hero && x != footer }
    new_content['composition'] = ([hero] + inner_content + [footer]).compact

    update(content: new_content.to_json)
  end
end

app/models/landing_page_version/section.rb
module LandingPageVersion::Section
  INFO = 'info'.freeze
  HERO = 'hero'.freeze
  FOOTER = 'footer'.freeze
  LISTINGS = 'listings'.freeze
  CATEGORIES = 'categories'.freeze
  LOCATIONS = 'locations'.freeze
  VIDEO = 'video'.freeze

  VARIATION_SINGLE_COLUMN = 'single_column'.freeze
  VARIATION_MULTI_COLUMN = 'multi_column'.freeze

  BACKGROUND_VARIATION_DARK = 'dark'.freeze
  BACKGROUND_VARIATION_LIGHT = 'light'.freeze
  BACKGROUND_VARIATION_TRANSPARENT = 'transparent'.freeze

  BACKGROUND_STYLE_IMAGE = 'image'.freeze
  BACKGROUND_STYLE_COLOR = 'color'.freeze
  BACKGROUND_STYLE_NONE = 'none'.freeze

  BACKGROUND_RESIZE_OPTIONS = {resize: '2000x1328'}.freeze
  LOCATION_IMAGE_RESIZE_OPTIONS = {resize: '1000x667'}.freeze
  CATEGORY_IMAGE_RESIZE_OPTIONS = {resize: '1000x667'}.freeze
end

app/models/landing_page_version/section_position.rb
class LandingPageVersion::SectionPosition
  include ActiveModel::Model

  attr_accessor(
    :id,
    :position,
    :kind,
    :variation
  )

  def removable?
    kind != LandingPageVersion::Section::HERO && kind != LandingPageVersion::Section::FOOTER
  end

  def sortable?
    removable? ? true: nil
  end
end

app/controllers/admin/landing_page_versions/sections_controller.rb
class Admin::LandingPageVersions::SectionsController < Admin::AdminBaseController
  before_action :ensure_plan
  before_action :set_selected_left_navi_link
  before_action :set_service

  def new
    @service.new_section
  end

  def create
    if @service.create
      redirect_to admin_landing_page_versions_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @service.update
      redirect_to admin_landing_page_versions_path
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to admin_landing_page_versions_path
  end

  private

  def set_selected_left_navi_link
    @selected_left_navi_link = "landing_page"
  end

  def set_service
    @service = CustomLandingPage::SectionService.new(
      community: @current_community,
      params: params)
    @presenter = CustomLandingPage::SectionPresenter.new(service: @service)
  end

  def ensure_plan
    unless @current_plan.try(:[], :features).try(:[], :landing_page)
      redirect_to admin_landing_page_path and return
    end
  end
end

app/controllers/admin/landing_page_versions_controller.rb
class Admin::LandingPageVersionsController < Admin::AdminBaseController
  before_action :ensure_plan
  before_action :set_selected_left_navi_link
  before_action :set_service

  def index; end

  def release
    if @service.release_landing_page_version
      link = ActionController::Base.helpers.link_to I18n.t('admin.communities.landing_pages.check_it_out'),
        landing_page_without_locale_path, target: '_blank', rel: 'noopener'
      flash[:notice] = I18n.t('admin.communities.landing_pages.latest_version_released', link: link).html_safe # rubocop:disable Rails/OutputSafety
    else
      flash[:error] = I18n.t('admin.communities.landing_pages.this_version_is_not_released')
    end
    redirect_to admin_landing_page_versions_path
  end

  def update
    @service.update_landing_page_version
    render body: 'OK'
  end

  private

  def set_selected_left_navi_link
    @selected_left_navi_link = "landing_page"
  end

  def set_service
    @service = CustomLandingPage::EditorService.new(
      community: @current_community,
      params: params)
    @service.ensure_latest_version_exists!
    @presenter = CustomLandingPage::EditorPresenter.new(service: @service)
  end

  def ensure_plan
    unless @current_plan.try(:[], :features).try(:[], :landing_page)
      redirect_to admin_landing_page_path and return
    end
  end
end

app/views/admin/landing_page_versions/sections/_background_color.haml
.row.bg-style-color
  .col-12
    %h4= t(".background_color")

.row.bg-style-color
  .col-12
    - link = link_to 'WebFx', "https://www.webfx.com/web-design/color-picker/", target: '_blank'
    = render partial: 'layouts/info_text', locals: {text: t(".background_color_info", link: link).html_safe}

.row.bg-style-color
  .col-12
    = form.label :background_color_string, class: 'after-info-text'
    = form.text_field :background_color_string, required: true

app/views/admin/landing_page_versions/sections/_background_image_overlay.haml
.row.bg-style-image
  .col-12
    %h4= t(".background_image")

.row.bg-style-image
  .col-12
    = render partial: 'layouts/info_text', locals: {text: t(".background_image_info")}

.row.bg-style-image
  .col-6
    #bg-image-preview
      - if presenter.section_background_image_present?
        %img{src: presenter.section_background_image_url}
    %p
      - if presenter.section_background_image_present?
        = t(".current_image", filename: presenter.section_background_image_filename)
      - else
        = t(".current_image", filename: t(".file_not_selected"))
  .col-6
    %label= t(".add_another_image")
    = file_field_tag "bg_image"
.row.bg-style-image
  .col-12
    %h4= t(".background_image_overlay")

.row.bg-style-image
  .col-12
    %label
      = form.radio_button :background_image_variation, LandingPageVersion::Section::BACKGROUND_VARIATION_DARK
      = t(".overlay_dark")
    %label
      = form.radio_button :background_image_variation, LandingPageVersion::Section::BACKGROUND_VARIATION_LIGHT
      = t(".overlay_light")
    %label
      = form.radio_button :background_image_variation, LandingPageVersion::Section::BACKGROUND_VARIATION_TRANSPARENT
      = t(".overlay_transparent")

app/views/admin/landing_page_versions/sections/_background_style.haml
.row
  .col-12
    %h4= t(".background_style")

.row
  %label
    = form.radio_button :background_style, LandingPageVersion::Section::BACKGROUND_STYLE_IMAGE, class: 'bg-style-selector'
    = t(".style_image")
  %label
    = form.radio_button :background_style, LandingPageVersion::Section::BACKGROUND_STYLE_COLOR, class: 'bg-style-selector'
    = t(".style_color")
  %label
    = form.radio_button :background_style, LandingPageVersion::Section::BACKGROUND_STYLE_NONE, class: 'bg-style-selector'
    = t(".style_none")

app/views/admin/landing_page_versions/sections/_categories.haml
- content_for :javascript do
  ST.FooterMenu.init();
  ST.LandingPageSectionEditor.initForm();

= render partial: 'id_field', locals: {presenter: presenter, form: form}

= render 'content'
.row
  .col-12
    = form.label :title
    = form.text_field :title
.row
  .col-12
    = form.label :paragraph
    = form.text_area :paragraph

= render partial: 'cta_button', locals: {form: form, presenter: presenter}

%h3= t(".include_title")

= render partial: 'layouts/info_text', locals: {text: t(".info_text") }

#menu-links-table
  .row.topbar-menu-container-padding.visible-tablet
    .col-10
      .col-6
        = label_tag do
          = t(".image")
      .col-6
        = label_tag do
          = t(".category")

.row#menu-links
  - @service.section.categories.each do |category|
    = form.fields_for :categories, category do |fields|
      = render "category", f: fields, disabled: false, presenter: presenter

  - new_category = @service.section.new_category
  = form.fields_for :categories, new_category, child_index: new_category.object_id do |fields|
    %script{type: "text/template", id: "new-footer-menu-link-tmpl"}
      = render "category", f: fields, disabled: false, presenter: presenter

.row#menu-links-empty
  .col-12
    = t(".empty")

.row
  .col-12
    = link_to t(".add"), '#', class: "add-fields",
      data: {id: new_category.object_id, template_id: "#new-footer-menu-link-tmpl"}

%input.custom-validation{type: 'hidden', data: {'msg-count-validation': t(".need_at_least_3_categories"), min: 3, 'counter-name': 'item_counter'}, 'count-validation': 'min', name: 'tc3'}
%input.custom-validation{type: 'hidden', data: {'msg-count-validation': t(".need_at_most_7_categories"), max: 7, 'counter-name': 'item_counter'}, 'count-validation': 'max', name: 'tc7'}

= render partial: 'background_selector', locals: {form: form, presenter: presenter}

app/views/admin/landing_page_versions/sections/_content.haml
.row.clp-section-content
  .col-12
    %h3= t('.title')

app/views/admin/landing_page_versions/sections/_cta_button.haml
.row
  .col-12
    %h3= t(".cta_button")

.row
  %label
    = form.check_box :cta_enabled, class: 'cta-select'
    = t(".cta_enabled")
  .cta-enabled
    = form.label :button_title
    = form.text_field :button_title, required: true, placeholder: t('.text_placeholder')

    = form.label :button_path_string
    = form.text_field :button_path_string, required: true, url: true, placeholder: t('.url_placeholder')

app/views/admin/landing_page_versions/sections/_footer.haml
- content_for :javascript do
  ST.FooterMenu.init();

= form.hidden_field :previous_id
= form.hidden_field :kind
= form.hidden_field :id, value: 'footer'

%h2= t(".footer_title")

.row
  .col-12
    %h3= t(".footer_style")

.row
  .col-12
    %label.inline
      = form.radio_button :theme, Community::FOOTER_DARK
      = t(".style_dark")
    %label.inline
      = form.radio_button :theme, Community::FOOTER_LIGHT
      = t(".style_light")
    %label.inline
      = form.radio_button :theme, Community::FOOTER_MARKETPLACE_COLOR
      = t(".style_marketplace_color")
    %label.inline
      = form.radio_button :theme, Community::FOOTER_LOGO
      = t(".style_logo")

%h3= t("admin.communities.footer.menu_links")
#menu-links-table
  .row.topbar-menu-container-padding.visible-tablet
    .col-10
      .col-6
        = label_tag do
          = t("admin.communities.footer.title")
      .col-6
        = label_tag do
          = t("admin.communities.footer.url")

.row#menu-links
  - @service.section.links.each do |footer_menu_link|
    = form.fields_for :links, footer_menu_link do |fields|
      = render "footer_menu_link", f: fields, disabled: false

  - new_footer_menu_link = @service.section.new_footer_menu_link
  = form.fields_for :links, new_footer_menu_link, child_index: new_footer_menu_link.object_id do |fields|
    %script{type: "text/template", id: "new-footer-menu-link-tmpl"}
      = render "footer_menu_link", f: fields, disabled: false

.row#menu-links-empty
  .col-12
    = t("admin.communities.menu_links.empty")

.row
  .col-12
    = link_to t("admin.communities.footer.add"), '#', class: "add-fields",
      data: {id: new_footer_menu_link.object_id, template_id: "#new-footer-menu-link-tmpl"}

%h3= t("admin.communities.footer.social_links")
#menu-links-table
  .row.topbar-menu-container-padding.visible-tablet
    .col-10
      .col-6
        = label_tag do
          = t("admin.communities.footer.social.title")
      .col-6
        = label_tag do
          = t("admin.communities.footer.social.url")

.row#social-links
  - @service.section.social.each do |social_link|
    = form.fields_for :social, social_link do |fields|
      = render "social_link", f: fields

%h3= t("admin.communities.footer.footer_copyright")
.row
  .col-12
    = form.text_area :copyright

app/views/admin/landing_page_versions/sections/_footer_menu_link.haml
- locale_value = @current_community.default_locale
.row.without-margin.menu-link-sortable.footer-menu-container{id: f.index, data: {"field-id": f.index, new: f.object.new_record? ? '1' : nil}}
  .col-10
    = f.hidden_field :id
    = f.hidden_field :sort_priority, class: 'sort-priority'
    = f.hidden_field :_destroy, class: 'destroy-record'
    .row
      .col-6
        %span.hidden-tablet
          = t("admin.communities.footer.title")
        = f.text_field :title,  required: true, maxlength: 255,
          placeholder: t("admin.communities.footer.title_placeholder", locale: locale_value),
          disabled: disabled

      .col-6
        %span.hidden-tablet
          = t("admin.communities.footer.url")
        = f.text_field :url, required: true, maxlength: 255, url: true,
          placeholder: t("admin.communities.footer.url_placeholder", locale: locale_value),
          disabled: disabled

  .col-2.menu-links-actions
    - link_class = "menu-link-without-locale-remove"

    = link_to "#", class: "menu-link-remove #{link_class}", tabindex: "-1" do
      = icon_tag("cross", ["icon-fix"])
    = link_to '#', class: "menu-link-action-up admin-sort-button", tabindex: "-1" do
      = icon_tag("directup", ["icon-fix"])
    = link_to '#', class: "menu-link-action-down admin-sort-button", tabindex: "-1" do
      = icon_tag("directdown", ["icon-fix"])

app/views/admin/landing_page_versions/sections/_form.haml
= form_for [:admin, presenter.landing_page_version, presenter.section], html: {multipart: true, class: "section-#{presenter.section.kind}-form edit_section"} do |form|
  - if presenter.section_info_single_column?
    = render 'single_column', presenter: presenter, form: form
  - elsif presenter.section_hero?
    = render 'hero', presenter: presenter, form: form
  - elsif presenter.section_footer?
    = render 'footer', presenter: presenter, form: form
  - elsif presenter.section_info_multi_column?
    = render 'multi_column', presenter: presenter, form: form
  - elsif presenter.section_listings?
    = render 'listings', presenter: presenter, form: form
  - elsif presenter.section_categories?
    = render 'categories', presenter: presenter, form: form
  - elsif presenter.section_locations?
    = render 'locations', presenter: presenter, form: form
  - elsif presenter.section_video?
    = render 'video', presenter: presenter, form: form

  .row
    .col-12
      .inline-button-container
        = form.button t("admin.communities.landing_pages.form.save")
      .inline-button-container
        = link_to admin_landing_page_versions_path,
          class: 'cancel-button' do
          .content
            = t("admin.communities.landing_pages.form.cancel")

app/views/admin/landing_page_versions/sections/_hero.haml
- content_for :javascript do
  ST.LandingPageSectionEditor.initHero();

= form.hidden_field :previous_id
= form.hidden_field :kind
= form.hidden_field :id, value: 'hero'

.row
  .col-12
    - link = link_to t('.basic_details_tab'), admin_details_edit_path, target: '_blank'
    %p= t(".hero_description", link: link).html_safe

= render partial: 'background_image_overlay', locals: {form: form, presenter: presenter}

.row
  .col-12
    %h3= t(".cta_button")

.row
  .col-12
    %label
      = form.radio_button :cta_button_type,
        LandingPageVersion::Section::Hero::BUTTON_TYPE_DEFAULT,
        cta_button_type_radio: true
      = t(".button_type.default")
    %label
      = form.radio_button :cta_button_type,
        LandingPageVersion::Section::Hero::BUTTON_TYPE_BUTTON,
        cta_button_type_radio: true
      = t(".button_type.button")
    %label
      = form.radio_button :cta_button_type,
        LandingPageVersion::Section::Hero::BUTTON_TYPE_NONE,
        cta_button_type_radio: true
      = t(".button_type.none")

.row.cta-default{class: form.object.cta_button_type_none? ? 'hidden' : ''}
  .col-12
    %h3= t(".button_content")

.row.cta-default{class: form.object.cta_button_type_none? ? 'hidden' : ''}
  .col-12
    = form.label :cta_button_text
    #cta-button-info{class: form.object.cta_button_type_button? ? 'hidden' : ''}
      = render partial: 'layouts/info_text', locals: {text: t(".cta_button_info")}
    = form.text_field :cta_button_text,
      placeholder:  t("admin.landing_page_versions.sections.cta_button.text_placeholder"),
      required: form.object.cta_button_type_button? ? true : nil

.row.cta-enabled{class: form.object.cta_button_type_button? ? '' : 'hidden'}
  .col-12
    = form.label :cta_button_url
    = form.text_field :cta_button_url, url: true,
      placeholder:  t("admin.landing_page_versions.sections.cta_button.url_placeholder"),
      required: true

app/views/admin/landing_page_versions/sections/_listings.haml
- content_for :javascript do
  ST.LandingPageSectionEditor.initForm();

= render partial: 'id_field', locals: {presenter: presenter, form: form}

= render 'content'
.row
  .col-12
    = form.label :title
    = form.text_field :title
.row
  .col-12
    = form.label :paragraph
    = form.text_area :paragraph

= render partial: 'cta_button', locals: {form: form, presenter: presenter}

.row
  .col-12
    %h3= t('.listings_to_feature')
    = render partial: 'layouts/info_text', locals: {text: t('.you_need_to_add_the_listing_ids')}

.row
  .col-6
    = form.label :listing_1_id
  .col-6
    = form.text_field :listing_1_id

.row
  .col-6
    = form.label :listing_2_id
  .col-6
    = form.text_field :listing_2_id

.row
  .col-6
    = form.label :listing_3_id
  .col-6
    = form.text_field :listing_3_id